### ISSUE TITLE
카카오 플랫폼 모듈

### ISSUE THREAD

**Issue by HwangWonYo** [kuj0210/IoT-Pet-Home-System#42]
제가 naver_talk_sdk 만들면서 카카오톡 모듈도 같이 만들었는데 
카톡 플랫폼을 계속 쓰시는 거라면 도움이 될거 같아요.

naver_talk_sdk와 다르게 kakaoplus 모듈은 사용자의 text에 따라 callback 함수를 따로 등록합니다.
callback 함수의 등록은 정규표현식이 적용되기 때문에 키워드 매칭에 유용할 수 있겠네요.
예를 들어 callback([(^Hello)]) 이라는 함수를 등록하면 Hello naver, Hello kuj와 같은 사용자의 text에 callback함수가 호출되는 방식입니다.
조금 더 customize가 필요하거나 모듈에 대해서 궁금하시면 comment 남겨주세요.

아래 링크입니다.
[kakaoplus](https://github.com/HwangWonYo/kakaoplus)

**Comment by kuj0210** [comment]
그 때 말씀드렸어야하는데 차 시간이랑 학교서류 때문에 말씀못드렸네요 진행하면서 이슈통해서 여쭤보겠습니다! 이슈주셔서 감사합니다
