### ISSUE TITLE
Performance of analyzing Korean Sentence issue

### ISSUE THREAD

**Issue by kuj0210** [kuj0210/IoT-Pet-Home-System#44]
i want use Morphological analyzer,  but analyzer is very slow.(Messenger will wait 5 seconds)
 
so i think we need to upgrade keyword analyzer which is we use now  

  | From Def ‘Class’ | From make ‘Object’ | From start‘Method’
-- | -- | -- | --
Time Test 1 | 3.22 S | 3.22 S | 3.10 S
Time Test 2 | 3.18 S | 3.21 S | 2.85 S
Time Test 3 | 3.10 S | 3.07 S | 2.99 S
Time Test 4 | 3.13 S | 3.20 S | 3.12 S
AVG | 3.1575 | 3.175 | 3.015

처음 계획은 형태소 분석기를 이용하여 문장분석할 계획이 였으나 성능이 낮아 메신저의 응답대기 시간을 만족하지 못합니다. 이에 키워드 분석을 유지하되, 요청추가가 쉽고 성능이 좋은 방식으로 개선해야합니다.

**Comment by HwangWonYo** [comment]
형태소 분석기 모듈 사용하신 건가요? konlpy?

**Comment by kuj0210** [comment]
@HwangWonYo  네네 안에 객체가 3개있던데 그중 잴빠른게 저 정도이네요 저기에 간단한 처리도해야하고 서버에서 결과받는 시간도 따지면 어려울듯해서 키워드 처리만 좀 고쳐서 사용할가 싶어요

**Comment by HwangWonYo** [comment]
@kuj0210 음.. 제 경험으로는 서버에 konlpy 모듈이 처음 메모리에 올라갈 때만 시간이 걸리고 그 이후에는 충분히 서비스 가능한 시간에 형태소 분석을 해주던데. 혹시 매번 모듈을 임포트하면서 스크립트 실행 단위로 테스트 해보신건 아닌가요?

**Comment by HwangWonYo** [comment]
아무튼 형태소 분석 말고 다른 방법을 찾으시는거면 https://dialogflow.com/ 를 추천합니다. keyword 매칭 user text를 관리하기 좋아요

**Comment by kuj0210** [comment]
@HwangWonYo  테스트시에는 class 정의, 객체생성, 메서드만 활용으로해서 3가지 시작점을 갖고 여러번 테스트 돌렸어요
실제로는 메서드 호출해서 처리할 생각이라서 메서드호출전에 시작잡고 후에 결과잡아서 차이값구했거든요 음... 다른방식으로 활용하면 시간이 되는까요? 우선 조금더 해봐야겠네요

**Comment by kuj0210** [comment]
@HwangWonYo 확인해보니 처음 호출후에 여러번 호출하면 0.5초이내로 답이나오내요 감사합니다!
