### ISSUE TITLE
new Sentence Analyzer

### ISSUE THREAD

**Issue by kuj0210** [kuj0210/IoT-Pet-Home-System#46]
this module is help by konlpy module 

[DIFFERENCE]
 it was analyzing just Sentence , now it get morpheme from konlpy module 
 so it's performance(accuracy) is enhanced

[bug] 
if not matching noun and verb, it can match wrong set by searching order
[for example]
n1 v1 n2 v2 -> (n1,v1) , (n2,v2) OK
n1 NO n2 v2 -> (n1,v2) ERR or (n2,v2) OK

konlpy의 모듈을 사용하여 정확도를 높였습니다.
지금까지는 단순하게 문장내의 키워드를 뽑아내는 식이었다면, 입력이 konlpy에서 받고 정확도 높고 유연하게 반응가능해서 대응가능합니다.

[버그]
명사,동사가 불안전한 매칭일 시에 잘못된 기능이 실행될 우려가 있습니다
1. 물 아...아니다 밥줘 > 물 줘 가 실행될 가능성이있습니다.

**Comment by KeonHeeLee** [comment]
I think that problem 1 may be solved by using stack.

**Comment by kuj0210** [comment]
No, it is Korean language problem
in korean, "and","or" is so many
[and] : 랑(rang) , 이고(ego), 그리고(gurigo)..... and They have different parts of speech.
so it is difficult ["feed water and food" => feed/water]
because they are also used in sentence for another parts and meaning ....

**Comment by KeonHeeLee** [comment]
I just looked up "**Google Cloud Natual Language API**" and it might be okay because it is a deep-learning mod., But the problem is the cost to you after 5,000 letters.

I'll put an API link below.
https://cloud.google.com/natural-language/
