### ISSUE TITLE
Unsafed HTTPS issues

### ISSUE THREAD

**Issue by KeonHeeLee** [kuj0210/IoT-Pet-Home-System#47]
I'm applying HTTPS for managing naver-talk, facebook, LINE messenger.
But I looked this part in chrome and Internet Explorer.

![default](https://user-images.githubusercontent.com/31424664/36063735-ed11a360-0ec3-11e8-95bb-0f8dfd4e5a22.PNG)

▲ Unsafed HTTPS in chrome

![03](https://user-images.githubusercontent.com/31424664/36063777-b2e3cafa-0ec4-11e8-88ac-2ae8c8c34d3a.PNG)

▲ Failure in kakao plus friends API test

This error generate API test error in kakao plus friends.
I can't understand why it is unsafed. Therefore I have been looking for this reason.
If you know this error's reason, please add comments at this issue T.T!

--------------------------------------------------------------------------------------------------

현재 네이버톡, 페이스북, 라인을 연동시키기 위해 HTTPS를 적용시키는 중입니다.
하지만 크롬이나 익스플로어에 이런 문제를 찾을 수 있었습니다.

그림1. 안전하지않은 HTTPS 문제 : 크롬에서
그림2. 카카오 플친 API 테스트 실패

이 에러는 카카오 플친 API 테스트 에러를 발생시킵니다.
왜 이게 불안전한 건지 이해를 못하겠습니다. 그러므로 이 이유를 찾고있습니다.
만약에 원인을 아신다면, 이슈에 코멘트 좀 남겨주세요 ㅜ.ㅜ!

**Comment by HwangWonYo** [comment]
SSL 인증은 성공하신건가요??
서버는 여전히 Flask 내장 서버를 사용하시죠?

**Comment by KeonHeeLee** [comment]
SSL 인증은 성공했습니다. 서버는 여전히 flask내장서버로 운영하고 있구요. 찾아보니깐 SSL인증서 내부의 암호화 문제라고들 하더라구요.

**Comment by HwangWonYo** [comment]
혹시 flask 에 ssl 인증서 경로를 알려주셨나요?
아니라면 http://flask.pocoo.org/snippets/111/ 이걸 참고하면 도움이될거 같아요. 
검색어는 flask ssl 이었습니다.

**Comment by KeonHeeLee** [comment]
@HwangWonYo Flask에 ssl인증서 경로라면 (cert,key) 이런식으로 경로를 넣어주긴했는데, 오류가 뜨더라구요.
주소 주신대로 한번 참고해보겠습니다. 감사합니다 :)

**Comment by KeonHeeLee** [comment]
아 완료됬습니당!
