### ISSUE TITLE
issue of camera function for analysing pet's action

### ISSUE THREAD

**Issue by kuj0210** [kuj0210/IoT-Pet-Home-System#52]
we adding new function sending alarm to user
for detecting pet's movement, we  use Ultrasonic sensor but it has some problem(health,accuracy...)
so we will use new way using camera

this 'code' can catch moving object but can not know it's location

![image](https://user-images.githubusercontent.com/33398268/36485242-0ac7ae92-175f-11e8-9c14-2f835daeb4b1.png)

현재 진행중인 알람기능에 대해서 현재는 대략적인 위치를 판별하기 위해 초음파센서를 사용하고 있습니다.
하지만 정확도가 낮고 장기간 이용시 건강상의 문제가 발생할 수도 있어 영상분석관련기능을 준비하고
있습니다.

현재진행 상황입니다. 움직임이 있는 물체를 남기고 배경을 지우는 것까지 성공입니다. 이후 이슈는 이 물체가 어디에 위치해있고 이 위치가 무엇을 뜻하는지 파악하는 것입니다.

[code]

import numpy as np
import cv2

cap = cv2.VideoCapture('test.mp4') #웹켐쓸거면인자 0
fgbg = cv2.createBackgroundSubtractorMOG2()

while (1):
    ret, frame = cap.read()

    fgmask = fgbg.apply(frame)

    kernel = np.ones((3, 3), np.float32) / 25
    dst = cv2.filter2D(fgmask, -1, kernel)
    edges = cv2.Canny(dst, 100, 200)

    #height, width, channel = edges.shape
    #for y in range(0, height):
        #for x in range(0, width):

    cv2.imshow('fgmask', frame)
    cv2.imshow('frame', fgmask)
    cv2.imshow('dst', dst)
    cv2.imshow('EDGES', edges)

    k = cv2.waitKey(30) & 0xff
    if k == 27:
        break

cap.release()
cv2.destroyAllWindows()

**Comment by KeonHeeLee** [comment]
Plus: Method;Using openCV is very efficient than using ultrasonic sensor.
Because this method is good at cost and pet's health.
But we need to think critical section issue by using camera; observation and taking picture.

**Comment by kuj0210** [comment]
but... it is so difficult to find what is pet and where is that my pet being ...
so i use MOG2 provided openCV, and erasing noise for enhance effect
