### ISSUE TITLE
To IoT-Pet-Home-System

### ISSUE THREAD

**Issue by HwangWonYo** [kuj0210/IoT-Pet-Home-System#53]
좋아요. 여느 오픈소스 운영 하듯이 진행하시면
본 프로젝트에 네이버 톡톡이랑 채팅 플랫폼이 잘 구현될 수 있도록 contribute 할게요 :)
계속 Issue랑 commit 보면서 follow하고 있습니다. 문서 잘 작성해주세요.
프로젝트랑 별개로 구체적으로 전할 이야기가 있으면 메일로 알려주세요. 
hollal0726@gmail.com 입니다 ㅎㅎ

**Comment by KeonHeeLee** [comment]
넵. 말씀주신대로 궁금한 사항이나 nta 관련 이슈가 생기면 repo에다가 남기고,
그 외의 사항은 메일로 전달하도록 하겠습니다.

**Comment by HwangWonYo** [comment]
네 그렇게 해요 :)
내일 오셔요? 저는 내일 회사가 빠르면 6시쯤에 끝나요.
혹시 시간 있으시면 버스 타시기 전에 근처 카페에서 이야기나 잠깐 할까요?

2018-02-22 0:37 GMT+09:00 K.H Lee <notifications@github.com>:

**Comment by KeonHeeLee** [comment]
오후에 밋업끝나면 7시쯤되긴한데, 끝나고 말씀드릴게요 :)
