### ISSUE TITLE
How about add CODE_OF_CONDUCT.md to IoT-Pet-Home-System?

### ISSUE THREAD

**Issue by bbvch13531** [kuj0210/IoT-Pet-Home-System#56]
Type of issue
 - Doc

Description
- I think opensource project should have code of conduct. 😄
How about add CODE_OF_CONDUCT.md to IoT-Pet-Home-System?
If this looks good on you, could I send PR that add CODE_OF_CONDUCT.md?

**Comment by KeonHeeLee** [comment]
**Thank you to your suggestion!**
I was actually thinking about where add code of description; 
1. To add in README.md (I think this is the way you suggested.)
2. To add in the top of each module(source code).

I'm going to talk to my team about what's better.
For the remaining schedule, I need to manage the project by referring to your ppt 
that you announced during the third 'meet up'.

**Comment by bbvch13531** [comment]
CODE_OF_CONDUCT.md

**Comment by KeonHeeLee** [comment]
I misunderstood and replied to you ... T.T

I'll find about 'CODE_OF_CONDUCT.md' and apply it.
Can I ask you a question about something I don't know?

And if I add CODE_OF_CONDUCT.md, I'll send PR that add it .
**Thanks again for your feedback!**

**Comment by bbvch13531** [comment]
Of course! You can contact me on facebook. My name is 허경영.Please send message
