### ISSUE TITLE
need to update "Read me"

### ISSUE THREAD

**Issue by kuj0210** [kuj0210/IoT-Pet-Home-System#62]
if who use our project, it is so difficult to search background-knowlege which is AWS server, certification, DB....
so i think it  must be Add more information in READ_ME for lowering entry barriers so that students with basic programming skills can easily using in assignments.

so i suggest,
 Create an account in AWS and operate https server
 how get certification for naver talk talk
 how add new messenger in system

No matter how good system, it is abandoned if it is difficult
we need to reduce the burden on users

+) Add setting method in README.md
- [x] AWS setting
- [x] DNS setting and applying HTTPS
- [x] How to Issue SSL Certificates
- [x] DB Query description

우리프로젝트를 사용하는 사람들이 처음 쓰기에는 요구사항이 많습니다.
그렇기 때문에 정말 기초 프로그래밍 지식을 가진 학생들이 과제에서 쉽게 쓸 수 있을 만큼 진입장벽을 낮출 필요가 있습니다.

가장 좋은것은 소스코드 정리이지만 이것은 진행중이고, 그 이외에도

 AWS 계정만들기, 사용법 및 HTTPS 서버열기 
naver talk talk 을 위한 인증서발급방법
새로운 메신저 추가방법(http 메신저추가방법 https 메신저 추가방법) 추가 후 DB 확장 등 

많은 기초설명이 누락되어 있습니다. 솔직하게 프로젝트 진행하고 있는 저희가 봐도 불친절하다 느낍니다. 

 fork 또는 opensource로 사용하기위해 구글링을 추가로 해야한다면  누가 우리프로젝트를 사용해줄가요? 저는 그렇기 때문에 추가 설명이 필요하다 느낍니다. 리드미에 한줄정도의 설명과 링크만 두어 리드미를 간결하게 유지하고 관련내용을 따로 정리해둘 필요가 있습니다.

사진을 보고 따라서 하면 충분히 따라할 수 있을 만큼 상세한 정보를 넣어야합니다.

**Comment by KeonHeeLee** [comment]
In addition to the installation method, I think it is better to create additional categories,
 such as how to set them up, and use it as a link method. I'll also work on that as we progress further.

**Comment by kuj0210** [comment]
It is natural. The reason for linking to "README" is to reduce the burden on the user. Make it easy to write and apply changes immediately

**Comment by KeonHeeLee** [comment]
I'll go ahead with this in the afternoon. I'm so sleepy coding until dawn. TT
