### ISSUE TITLE
New Korean analyzer

### ISSUE THREAD

**Issue by kuj0210** [kuj0210/IoT-Pet-Home-System#66]
[KoNpy License image]

![image](https://user-images.githubusercontent.com/33398268/36959640-6920bbd4-2086-11e8-9c2c-4a3bda3ac470.png)

![image](https://user-images.githubusercontent.com/33398268/36959795-47316ee6-2087-11e8-8be9-fd4f7072cb89.png)
[link for License]
https://olis.or.kr/license/Detailselect.do?lId=1072

[for  install KoNLpy]
http://konlpy-ko.readthedocs.io/ko/v0.4.3/install/

[source code (New Korean analyzer and Tester)]
[NEWCOMP.zip](https://github.com/kuj0210/IoT-Pet-Home-System/files/1779767/NEWCOMP.zip)

[result of Test]
![image](https://user-images.githubusercontent.com/33398268/36959691-bcbbb65e-2086-11e8-92ff-8107fc75347b.png)

[Bug]
This should add processing for " 과(와)".

**Comment by KeonHeeLee** [comment]
I'll add this issue at pull request and other documents.

**Comment by seok8418** [comment]
[Bug]
You must add a process for " 과 " in " 밥과 물을 줘"

**Comment by seok8418** [comment]
You must add a process for " 과 " in " 밥과 물을 줘"

![image](https://user-images.githubusercontent.com/34744421/36978147-e1d5e5c8-20c6-11e8-9fc1-189b23e82b0d.png)
![image](https://user-images.githubusercontent.com/34744421/36978193-0397474c-20c7-11e8-9b59-207529fe1070.png)

**Comment by kuj0210** [comment]
i miss gua(과), wa(와)... i will fix them!

**Comment by KeonHeeLee** [comment]
Umm.. so I'll hand out this version;pre-release.
