### ISSUE TITLE
Troubleshooting " AND(wa(와) gua(과)) "

### ISSUE THREAD

**Issue by kuj0210** [kuj0210/IoT-Pet-Home-System#74]
![image](https://user-images.githubusercontent.com/33398268/37191255-c9392326-23a1-11e8-9558-3ef453c6ed3e.png)

기존의 모듈은 연결조사만 확인했었는데 와/과 는 조사의 분류가 다르게되어 누락되어있었습니다. 
관측 조사를 확장하여 해당문제를 해결하였습니다.

current module only checked it partially So  wa(와) and gua(과) was passed,
i expand module and solved it.

[code]
[newCOMP.zip](https://github.com/kuj0210/IoT-Pet-Home-System/files/1795670/newCOMP.zip)

License #66

**Comment by KeonHeeLee** [comment]
I'll put it in "Pull requests".
