### ISSUE TITLE
Disposal - hair loss conditioner

### ISSUE THREAD

**Issue by ras120** [kuj0210/IoT-Pet-Home-System#76]
Disposal - hair loss conditioner
폐기 - 탈모 컨디셔너

Reason for disposal -  
	There is already an app that measures the image of the process of hair loss and the community is already quite active.
	Our plan is just a combination of the two.
        The difference is that they communicate directly with doctors and take advantage of the popularity of doctors.
        Most of the plans already exist, there are not many differences and it is difficult to realize.

폐기 사유
	탈모진행을 이미지로 측정하는 앱이 이미 있고 커뮤니티도 상당히 활성화 된것이 이미 있다.
	우리의 계획은 이 둘을 합친 형태일 뿐이다. 
	차이점은 의사와의 직접소통하고 의사들의 인기도를 이용하는 정도이다.
	계획의 대부분이 이미 존재하고 차이점이 크지않고 실현하기 어려움.
            

-------------------------------------------------------------------------------------------------
	Below is a survey
-------------------------------------------------------------------------------------------------

Related Image Processing Technology
사용할 영상처리 기술

  ILLUMINATION CORRECTION - Adjust the lighting effect of an image to make a clear measurement
  조명 보정 - 이미지의 조명효과를 조정하여 확실한 측정
	https://clouard.users.greyc.fr/Pantheon/experiments/illumination-correction/index-en.html

  color detection - Estimate hair loss progression by measuring density of hair thinning using color difference
  색 검출  - 색상 차이를 이용하여 머리숱의 밀도를 측정하여 탈모 진행을 추정
	https://www.opencv-srf.com/2010/09/object-detection-using-color-seperation.html

  edge detection
  에지검출 
	https://docs.opencv.org/3.3.1/da/d22/tutorial_py_canny.html
		

Related apps - Play Store   (in Korea)
관련 앱 - 플레이 스토어

  탈모 탈출 : 이상적인 헤어스타일로 새로운 자신이 되자
   -설명 : 시뮬레이션 게임. 플레이를 하면서 탈모를 위한 정보를 제공하고 사용자가 습득할 수 있게 함.
   -내용 : 인터넷을 통해 만나게 된 여자와 1개월 뒤 만나게 되어 그 때까지 머리숱을 늘려라!

  탈모자가진단
   -설명 : 각 성별에 맞는 테스트를 진행함. 테스트는 설문형식. 테스트 결과에는 위험지수와 3~5줄 정도의 설명. 샴푸광고

  모발모발 - 탈모테스트, 탈모측정기
   -설명 : 카메라(즉석촬영), 앨범의 이미지로 탈모율을 보여줌. 유저들의 탈모율 랭킹 기능이 있음.

Other information
그외 정보
	hair loss statistics video - EBS video
	탈모 통계 영상 - EBS 동영상
		http://terms.naver.com/entry.nhn?docId=2450376&cid=51616&categoryId=51616
	
	Health Insurance Corporation (jisik-in) - hair loss Information
	건강보험공단 (지식in) - 탈모관련
		http://hi.nhis.or.kr/cc/ggpcc003/ggpcc003_m03.do
	
	Naver jisik-in - hair loss statistics 2001 ~ 2008
	네이버 지식인 - 탈모 통계 2001 ~ 2008
		http://kin.naver.com/qna/detail.nhn?d1id=8&dirId=8030206&docId=103972584&sp=1&sort=default&sid=SqbS7hQnV%2BJ7kT0SGe1WsQ%3D%3D&rank=1&pid=Tq5YvlpVuF4ssuw0w6dssssst1d-497528&search_sort=0&qb=7YOI66qoIO2GteqzhA%3D%3D&spq=1&section=kin&enc=utf8

	DC inside hair loss gallery - hair loss community
	DC inside 탈모갤러리 - 탈모 커뮤니티
		http://gall.dcinside.com/board/lists/?id=alopecia&page=1&exception_mode=recommend
	
	Daedamo - hair loss community webpage
	대다모  - 탈모 커뮤니티 웹페이지
		http://daedamo.com/new/main_daedamo.php

**Comment by KeonHeeLee** [comment]
I don't think it's related to the repo here.
