### ISSUE TITLE
Moving to a server environment

### ISSUE THREAD

**Issue by kuj0210** [kuj0210/IoT-Pet-Home-System#84]
we are using  AWS but it was  memory issue
so i suggest changing environment to window's 

i will get a public ip(school ip) with port(443/ 8080/ 8888) and move server 

학교 아이피 포트 뚫는중 
아마 금요일쯤 받음 나중에 SSL 관련해서 이슈하겠음

**Comment by KeonHeeLee** [comment]
Moving our server to woo-jin's lab server is complete. 
And applying HTTPS server is also complete.
