### ISSUE TITLE
Fix screenshot thread module.

### ISSUE THREAD

**Issue by KeonHeeLee** [kuj0210/IoT-Pet-Home-System#86]
## Expected Behavior
 We can use the function that it is available to catch screenshot and send the screenshot to user.

**Comment by KeonHeeLee** [comment]
~ Sun

**Comment by kuj0210** [comment]
when you upload code, i hope you to test  
버그테스트 안하고올리면 진짜 죽여버릴거야

**Comment by KeonHeeLee** [comment]
OK TT

**Comment by kuj0210** [comment]
if you can't keep deadline i will kill it is not kidding 
어린이날까지 못하면 진짜 죽일거야
