### ISSUE TITLE
Send image method in flask framework.

### ISSUE THREAD

**Issue by KeonHeeLee** [kuj0210/IoT-Pet-Home-System#91]
I analyzed the methods of sending image from flask framework environment. And I discovered some features of flask framework and I suggest one of method.

As we know, one of method that send file to client, is supported in flask framework. This method name is "send_file()" and "send_from_directory()". This methods only support filename metioned in url rule. In other words, it is available to send a metioned filename, if you have this file on the mentioned directory.
 Therefore I suggested that we must make a thread related on sending or recieving image.
Forthemore, this method was suggested by JinHyeok who is your lab co-worker. Flask's "send_file()" or "send_from_directory()" method is only useful, if we provide a link to clients. If it is not, we must make a thread that I suggested method.

- Summary theorem
1. "send_file" or "send_from_directory" is only useful, if we provide a link that is available to download file.
2. We must make thread related on uploading or recieving file.

**Comment by KeonHeeLee** [comment]
https://github.com/KeonHeeLee/test-to-send-or-recieve-image
This is my test repo.

**Comment by kuj0210** [comment]
ㅇㅇ DB쿼리랑 최대한 빠르게 처리해줘 버그없겠금 테스트 필하면 말해 연구실서 깃 클론해서 하자\
