### ISSUE TITLE
change server structure

### ISSUE THREAD

**Issue by kuj0210** [kuj0210/IoT-Pet-Home-System#93]
![image](https://user-images.githubusercontent.com/33398268/42866299-27347716-8aa7-11e8-9dc1-96bd3b267b25.png)

Our original server was a two-way communication between the chat server and the pet home server.

However, it is troublesome for the user to make some settings by using fixed IP.

We are going to use the cloud approach to solve this.

**Comment by KeonHeeLee** [comment]
Main server refactorying was complete.
