### ISSUE TITLE
Status 400 code occurs.

### ISSUE THREAD

**Issue by KeonHeeLee** [kuj0210/IoT-Pet-Home-System#94]
- Client
![02](https://user-images.githubusercontent.com/31424664/43000371-20ae8a1a-8c5c-11e8-813b-dc29cdbf4d4e.PNG)

I will request rendering html template to server.

- Server

![01](https://user-images.githubusercontent.com/31424664/43000176-684041e4-8c5b-11e8-9fd5-ca091a67ea88.PNG)

But this error occurs...

This case is HTTP error code:400 (Bad request). This condition of error code is occured,
if I request rendering html template to server. I have found the solution of this error...

**Comment by kuj0210** [comment]
못고치면 그냥 쉽게 죽을 생각하지마.... 정말 고통스럽게 말려주길거다... 흐으 그거 끝나면 막 테스트 ㄱㄱ 어제 간략하게 테스트했을 때 내꺼 고친거는 에러없었음 기능모듈 / 새로만든 모듈 다합쳐서 테스트하자

**Comment by KeonHeeLee** [comment]
complete!
