### ISSUE TITLE
 Reorganization READ ME 

### ISSUE THREAD

**Issue by kuj0210** [kuj0210/IoT-Pet-Home-System#96]
## main
Introduction
&nbsp; &nbsp; [project]
 &nbsp; &nbsp;[module/system] 
Features
Requirement : 
&nbsp; &nbsp;[HW]
&nbsp; &nbsp;&nbsp; &nbsp;[server]
&nbsp; &nbsp;&nbsp; &nbsp;[petHome(Raspberry Pi)] 
&nbsp; &nbsp;[SW]
&nbsp; &nbsp;&nbsp; &nbsp;[server]
&nbsp; &nbsp;&nbsp; &nbsp;[petHome(Raspberry Pi)] 
Pet House Structure
Client &Server Structure
How to use 
Notes - version information / how to get module
promotion – PR in Korean and Englishfor user
LICENSE

###chatting bot
Introduction - what is this?
Requirement 
How to get SSL
installation and use procedures
Introducing Internal Modules
Membership Management and DB Explanation
#### Each subdirectory
Introducing the functions of each module
   

###petHome
how to make house
installation for Raspberry Pi
sensor connection
#### Each subdirectory
Introducing the functions of each module

# Each subdirectory style Example
### Serial : 
This is a unique number for the pet home. This value is issued and managed by the DB administrator. There is no value condition, it is a string 
### UserKey : 
This is a unique number for User. 

There is no condition, and it is a unique value issued directly by each messenger to distinguish or PUSH the user.

### &nbsp;&nbsp;userFromSerial(Serial)
&nbsp; &nbsp;&nbsp; &nbsp; input: Serial(str) , output UserKey(str)
&nbsp; &nbsp;&nbsp; &nbsp; Description: Get the UserKey from Serial with the query statement referenced in DB

### &nbsp;&nbsp;userFromEmail(Email)	
&nbsp; &nbsp;&nbsp; &nbsp; input: Email(str) , output UserKey(str)
&nbsp; &nbsp;&nbsp; &nbsp; Description: ....
### &nbsp;&nbsp;userFromUserKey(userKey)	
...

**Comment by KeonHeeLee** [comment]
Chatting Bot part was complete.
